using System;
using System.Linq;
using System.Text;
using BagIt.Models;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Globalization;

namespace BagIt.Services
{
    public class ProductInventory
    {
        private static ProductInventory instance;
		List<Product> products = new List<Product>
		{    new Product { Name = "Kombucha",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/001-kombucha.svg" },
			 new Product { Name = "Milk Box",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/002-milk__box.svg" },
			 new Product { Name = "Coffee",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/003-coffee.svg" },
			 new Product { Name = "Wine",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/004-wine.svg" },
			 new Product { Name = "Wine",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/005-wine.svg" },
			 new Product { Name = "Champagne",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/006-champagne.svg" },
			 new Product { Name = "Martini",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/007-martini.svg" },
			 new Product { Name = "Cosmopolitan",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/008-cosmopolitan.svg" },
			 new Product { Name = "Energy Drink",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/009-energy__drink.svg" },
			 new Product { Name = "Cappuccino",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/010-cappuccino.svg" },
			 new Product { Name = "Cola",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/011-cola.svg" },
			 new Product { Name = "Cola",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/012-cola.svg" },
			 new Product { Name = "Matcha",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/013-matcha.svg" },
			 new Product { Name = "Chocolate Milk",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/014-chocolate__milk.svg" },
			 new Product { Name = "Mimosa",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/015-mimosa.svg" },
			 new Product { Name = "Soda",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/016-soda.svg" },
			 new Product { Name = "Sangria",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/017-sangria.svg" },
			 new Product { Name = "Beer",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/018-beer.svg" },
			 new Product { Name = "Lemonade",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/019-lemonade.svg" },
			 new Product { Name = "Tea",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/020-tea.svg" },
			 new Product { Name = "Milkshake",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/021-milkshake.svg" },
			 new Product { Name = "Coffee",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/022-coffee.svg" },
			 new Product { Name = "Bubble Tea",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/023-bubble__tea.svg" },
			 new Product { Name = "Mojito",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/024-mojito.svg" },
			 new Product { Name = "Latte Macchiato",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/025-latte__macchiato.svg" },
			 new Product { Name = "Infusion",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/026-infusion.svg" },
			 new Product { Name = "Horchata",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/027-horchata.svg" },
			 new Product { Name = "Ice Tea",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/028-Ice__Tea.svg" },
			 new Product { Name = "Smoothie",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/029-smoothie.svg" },
			 new Product { Name = "Beer",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/030-beer.svg" },
			 new Product { Name = "Milk",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/031-milk.svg" },
			 new Product { Name = "Milkshake",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/032-milkshake.svg" },
			 new Product { Name = "Strawberry Milk",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/033-strawberry__milk.svg" },
			 new Product { Name = "Whiskey",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/034-whiskey.svg" },
			 new Product { Name = "Dalgona",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/035-dalgona.svg" },
			 new Product { Name = "Smoothie",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/036-smoothie.svg" },
			 new Product { Name = "Iced Coffee",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/037-iced__coffee.svg" },
			 new Product { Name = "Juice Box",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/038-juice__box.svg" },
			 new Product { Name = "Cocktail",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/039-cocktail.svg" },
			 new Product { Name = "Soda",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/040-soda.svg" },
			 new Product { Name = "Tea Pot",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/041-tea__pot.svg" },
			 new Product { Name = "Punch",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/042-punch.svg" },
			 new Product { Name = "Ramune",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/043-ramune.svg" },
			 new Product { Name = "Coconut",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/044-coconut.svg" },
			 new Product { Name = "Margarita",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/045-margarita.svg" },
			 new Product { Name = "Hot Chocolate",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/046-hot__chocolate.svg" },
			 new Product { Name = "Water",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/047-water.svg" },
			 new Product { Name = "Cocktail Shaker",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/048-cocktail__shaker.svg" },
			 new Product { Name = "Cream Soda",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/049-cream__soda.svg" },
			 new Product { Name = "Orange Juice",  Category = "Beverages", Quantity = 1, Icon = "/icons/Beverages/050-orange__juice.svg" },
			 new Product { Name = "Apple",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/001-apple.svg" },
			 new Product { Name = "Asparagus",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/001-asparagus.svg" },
			 new Product { Name = "Broccoli",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/002-broccoli.svg" },
			 new Product { Name = "Pomegranate",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/002-pomegranate.svg" },
			 new Product { Name = "Cabbage",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/003-cabbage.svg" },
			 new Product { Name = "Tomato",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/003-tomato.svg" },
			 new Product { Name = "Cabbage",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/004-cabbage.svg" },
			 new Product { Name = "Cucumber",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/004-cucumber.svg" },
			 new Product { Name = "Cabbage",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/005-cabbage.svg" },
			 new Product { Name = "Carrot",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/005-carrot.svg" },
			 new Product { Name = "Cauliflower",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/006-cauliflower.svg" },
			 new Product { Name = "Radish",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/006-radish.svg" },
			 new Product { Name = "Celery",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/007-celery.svg" },
			 new Product { Name = "Eggplant",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/007-eggplant.svg" },
			 new Product { Name = "Celery",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/008-celery.svg" },
			 new Product { Name = "Pumpkin",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/008-pumpkin.svg" },
			 new Product { Name = "Bell",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/009-bell-pepper.svg" },
			 new Product { Name = "Chili",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/009-chili.svg" },
			 new Product { Name = "Corn",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/010-corn.svg" },
			 new Product { Name = "Garlic",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/010-garlic.svg" },
			 new Product { Name = "Corn",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/011-corn.svg" },
			 new Product { Name = "Cucumber",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/011-cucumber.svg" },
			 new Product { Name = "Eggplant",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/012-eggplant.svg" },
			 new Product { Name = "Pear",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/012-pear.svg" },
			 new Product { Name = "Leek",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/013-leek.svg" },
			 new Product { Name = "Potato",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/013-potato.svg" },
			 new Product { Name = "Banana",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/014-banana.svg" },
			 new Product { Name = "Garlic",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/014-garlic.svg" },
			 new Product { Name = "Cherry",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/015-cherry.svg" },
			 new Product { Name = "Shallot",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/015-shallot.svg" },
			 new Product { Name = "Blueberry",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/016-blueberry.svg" },
			 new Product { Name = "Ginger",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/016-ginger.svg" },
			 new Product { Name = "Fig",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/017-fig.svg" },
			 new Product { Name = "Kale",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/017-kale.svg" },
			 new Product { Name = "Lettuce",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/018-lettuce.svg" },
			 new Product { Name = "Watermelon",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/018-watermelon.svg" },
			 new Product { Name = "Champignon",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/019-champignon.svg" },
			 new Product { Name = "Papaya",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/019-papaya.svg" },
			 new Product { Name = "Mushroom",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/020-mushroom.svg" },
			 new Product { Name = "Raspberry",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/020-raspberry.svg" },
			 new Product { Name = "Bell Pepper",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/021-Bell__pepper.svg" },
			 new Product { Name = "Strawberry",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/021-strawberry.svg" },
			 new Product { Name = "Coconut",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/022-coconut.svg" },
			 new Product { Name = "Sweet Potato",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/022-sweet__potato.svg" },
			 new Product { Name = "Apricot",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/023-apricot.svg" },
			 new Product { Name = "Pumpkin",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/023-pumpkin.svg" },
			 new Product { Name = "Beetroot",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/024-beetroot.svg" },
			 new Product { Name = "Mango",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/024-mango.svg" },
			 new Product { Name = "Beetroot",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/025-beetroot.svg" },
			 new Product { Name = "Broccoli",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/025-broccoli.svg" },
			 new Product { Name = "Olives",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/026-olives.svg" },
			 new Product { Name = "Radish",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/026-radish.svg" },
			 new Product { Name = "Beetroot",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/027-beetroot.svg" },
			 new Product { Name = "Cauliflower",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/027-cauliflower.svg" },
			 new Product { Name = "Ginger",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/028-ginger.svg" },
			 new Product { Name = "Wasabi",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/028-wasabi.svg" },
			 new Product { Name = "Garlic",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/029-garlic-1.svg" },
			 new Product { Name = "Zucchini",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/029-zucchini.svg" },
			 new Product { Name = "Spinach",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/030-spinach.svg" },
			 new Product { Name = "Asparagus",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/031-asparagus.svg" },
			 new Product { Name = "Chili",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/032-chili-pepper.svg" },
			 new Product { Name = "Peas",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/033-peas.svg" },
			 new Product { Name = "Orange",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/034-orange.svg" },
			 new Product { Name = "Carrot",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/035-carrot.svg" },
			 new Product { Name = "Turnip",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/036-turnip.svg" },
			 new Product { Name = "Beet",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/037-beet.svg" },
			 new Product { Name = "Zucchini",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/038-zucchini.svg" },
			 new Product { Name = "Celery",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/039-celery.svg" },
			 new Product { Name = "Melon",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/040-melon.svg" },
			 new Product { Name = "Carambola",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/041-carambola.svg" },
			 new Product { Name = "Passion",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/042-passion-fruit.svg" },
			 new Product { Name = "Rambutan",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/043-rambutan.svg" },
			 new Product { Name = "Mangosteen",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/044-mangosteen.svg" },
			 new Product { Name = "Lemon",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/045-lemon.svg" },
			 new Product { Name = "Plum",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/046-plum.svg" },
			 new Product { Name = "Sweet",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/047-sweet-potato.svg" },
			 new Product { Name = "Brussels",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/048-brussels-sprouts.svg" },
			 new Product { Name = "Pumpkin",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/049-pumpkin-1.svg" },
			 new Product { Name = "Caper",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/050-caper.svg" },
			 new Product { Name = "Arugula",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/051-arugula.svg" },
			 new Product { Name = "Dill",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/052-dill.svg" },
			 new Product { Name = "Parsley",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/053-parsley.svg" },
			 new Product { Name = "Basil",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/054-basil.svg" },
			 new Product { Name = "Basil",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/055-basil-1.svg" },
			 new Product { Name = "Avocado",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/056-avocado.svg" },
			 new Product { Name = "Kohlrabi",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/057-kohlrabi.svg" },
			 new Product { Name = "Squash",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/058-squash.svg" },
			 new Product { Name = "Passion",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/059-passion-fruit-1.svg" },
			 new Product { Name = "Gooseberry",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/060-gooseberry.svg" },
			 new Product { Name = "Berries",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/061-berries.svg" },
			 new Product { Name = "Berries",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/062-berries-1.svg" },
			 new Product { Name = "Kumquat",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/063-kumquat.svg" },
			 new Product { Name = "Goji",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/064-goji.svg" },
			 new Product { Name = "Grapefruit",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/065-grapefruit.svg" },
			 new Product { Name = "Lime",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/066-lime.svg" },
			 new Product { Name = "Kiwi",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/067-kiwi.svg" },
			 new Product { Name = "Peach",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/068-peach.svg" },
			 new Product { Name = "Date",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/069-date.svg" },
			 new Product { Name = "Chestnut",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/070-chestnut.svg" },
			 new Product { Name = "Quince",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/071-quince.svg" },
			 new Product { Name = "Guava",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/072-guava.svg" },
			 new Product { Name = "Persimmon",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/073-persimmon.svg" },
			 new Product { Name = "Leek",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/074-leek.svg" },
			 new Product { Name = "Rhubarb",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/075-rhubarb.svg" },
			 new Product { Name = "Lettuce",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/076-lettuce.svg" },
			 new Product { Name = "Horseradish",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/077-horseradish.svg" },
			 new Product { Name = "Pineapple",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/078-pineapple.svg" },
			 new Product { Name = "Radish",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/079-radish-1.svg" },
			 new Product { Name = "Grapes",  Category = "Fruits & Vegetables", Quantity = 1, Icon = "/icons/Fruits__&__Vegetables/080-grapes.svg" },
			 new Product { Name = "Almond",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/001-almond.svg" },
			 new Product { Name = "Saffron",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/001-saffron.svg" },
			 new Product { Name = "Aniseed",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/002-aniseed.svg" },
			 new Product { Name = "Saffron",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/002-saffron.svg" },
			 new Product { Name = "Green Onion",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/003-green__onion.svg" },
			 new Product { Name = "Spices",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/003-spices.svg" },
			 new Product { Name = "Basil",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/004-basil.svg" },
			 new Product { Name = "Clove",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/004-clove.svg" },
			 new Product { Name = "Bay",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/005-bay.svg" },
			 new Product { Name = "Garlic",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/005-garlic.svg" },
			 new Product { Name = "Chestnut",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/006-chestnut.svg" },
			 new Product { Name = "Ginger",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/006-ginger.svg" },
			 new Product { Name = "Chia",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/007-chia.svg" },
			 new Product { Name = "Mint",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/007-mint.svg" },
			 new Product { Name = "Chilli",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/008-chilli.svg" },
			 new Product { Name = "Cinnamon",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/008-cinnamon.svg" },
			 new Product { Name = "Cinnamon",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/009-cinnamon.svg" },
			 new Product { Name = "Vanilla",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/009-vanilla.svg" },
			 new Product { Name = "Clove",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/010-clove.svg" },
			 new Product { Name = "Parsley",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/010-parsley.svg" },
			 new Product { Name = "Basil",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/011-basil.svg" },
			 new Product { Name = "Cocoa",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/011-cocoa.svg" },
			 new Product { Name = "Coconut",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/012-coconut.svg" },
			 new Product { Name = "Tamarind",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/012-tamarind.svg" },
			 new Product { Name = "Anise",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/013-anise.svg" },
			 new Product { Name = "Ginger",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/013-ginger.svg" },
			 new Product { Name = "Goji",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/014-goji.svg" },
			 new Product { Name = "Nutmeg",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/014-nutmeg.svg" },
			 new Product { Name = "Hand",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/015-hand.svg" },
			 new Product { Name = "Rosemary",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/015-rosemary.svg" },
			 new Product { Name = "Arugula",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/016-arugula.svg" },
			 new Product { Name = "Hazelnut",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/016-hazelnut.svg" },
			 new Product { Name = "Chili Pepper",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/017-chili__pepper.svg" },
			 new Product { Name = "Herbs",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/017-herbs.svg" },
			 new Product { Name = "Oregano",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/018-oregano.svg" },
			 new Product { Name = "Spices",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/018-spices.svg" },
			 new Product { Name = "Mint",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/019-mint.svg" },
			 new Product { Name = "Savory",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/019-savory.svg" },
			 new Product { Name = "Cumin",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/020-cumin.svg" },
			 new Product { Name = "Mustard",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/020-mustard.svg" },
			 new Product { Name = "Nut Free",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/021-nut__free.svg" },
			 new Product { Name = "Nut",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/022-nut.svg" },
			 new Product { Name = "Peanut",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/023-peanut.svg" },
			 new Product { Name = "Pepper",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/024-pepper.svg" },
			 new Product { Name = "Pistachio",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/025-pistachio.svg" },
			 new Product { Name = "Saffron",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/026-saffron.svg" },
			 new Product { Name = "Soy",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/027-soy.svg" },
			 new Product { Name = "Spice",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/028-spice.svg" },
			 new Product { Name = "Spices",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/029-spices.svg" },
			 new Product { Name = "Sunflower",  Category = "Herbs & Spices", Quantity = 1, Icon = "/icons/Herbs__&__Spices/030-sunflower.svg" },
			 new Product { Name = "Wheat",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/001-wheat.svg" },
			 new Product { Name = "Shovel",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/002-shovel.svg" },
			 new Product { Name = "Carrots",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/003-carrots.svg" },
			 new Product { Name = "Watering Can",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/004-watering__can.svg" },
			 new Product { Name = "Fence",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/005-fence.svg" },
			 new Product { Name = "Eggs",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/006-eggs.svg" },
			 new Product { Name = "Boots",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/007-boots.svg" },
			 new Product { Name = "Barrel",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/008-barrel.svg" },
			 new Product { Name = "Sprout",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/009-sprout.svg" },
			 new Product { Name = "Honey",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/010-honey.svg" },
			 new Product { Name = "Tomato",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/011-tomato.svg" },
			 new Product { Name = "Seeds",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/012-seeds.svg" },
			 new Product { Name = "Barn",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/013-barn.svg" },
			 new Product { Name = "Pig",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/014-pig.svg" },
			 new Product { Name = "Basket",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/015-basket.svg" },
			 new Product { Name = "Tractor",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/016-tractor.svg" },
			 new Product { Name = "Milk",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/017-milk.svg" },
			 new Product { Name = "Sprayer",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/018-sprayer.svg" },
			 new Product { Name = "Sprout",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/019-sprout.svg" },
			 new Product { Name = "Jam",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/020-jam.svg" },
			 new Product { Name = "Hay",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/021-hay.svg" },
			 new Product { Name = "Cheese",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/022-cheese.svg" },
			 new Product { Name = "Eggs",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/023-eggs.svg" },
			 new Product { Name = "Seeding",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/024-seeding.svg" },
			 new Product { Name = "Scissors",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/025-scissors.svg" },
			 new Product { Name = "Wood Axe",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/026-wood__axe.svg" },
			 new Product { Name = "Pumpkin",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/027-pumpkin.svg" },
			 new Product { Name = "Bucket",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/028-bucket.svg" },
			 new Product { Name = "Pickup Truck",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/029-pickup__truck.svg" },
			 new Product { Name = "Hat",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/030-hat.svg" },
			 new Product { Name = "Windmill",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/031-windmill.svg" },
			 new Product { Name = "Milk",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/032-milk.svg" },
			 new Product { Name = "Silo",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/033-silo.svg" },
			 new Product { Name = "Well",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/034-well.svg" },
			 new Product { Name = "Hand Gloves",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/035-hand__gloves.svg" },
			 new Product { Name = "Hose",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/036-hose.svg" },
			 new Product { Name = "Sickle",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/037-Sickle.svg" },
			 new Product { Name = "Bird House",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/038-bird__house.svg" },
			 new Product { Name = "Pruners",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/039-pruners.svg" },
			 new Product { Name = "Trowel",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/040-trowel.svg" },
			 new Product { Name = "Scarecrow",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/041-scarecrow.svg" },
			 new Product { Name = "Weather Vane",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/042-weather__vane.svg" },
			 new Product { Name = "Irrigation",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/043-irrigation.svg" },
			 new Product { Name = "Sawing",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/044-sawing.svg" },
			 new Product { Name = "Honeycomb",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/045-honeycomb.svg" },
			 new Product { Name = "Fertilizer",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/046-fertilizer.svg" },
			 new Product { Name = "Fork",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/047-fork.svg" },
			 new Product { Name = "Corn",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/048-corn.svg" },
			 new Product { Name = "Farmer",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/049-farmer.svg" },
			 new Product { Name = "Drone",  Category = "Home & Garden", Quantity = 1, Icon = "/icons/Home__&__Garden/050-drone.svg" },
			 new Product { Name = "Beef",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/001-beef.svg" },
			 new Product { Name = "Shrimp",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/001-shrimp.svg" },
			 new Product { Name = "Catfish",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/002-catfish.svg" },
			 new Product { Name = "Cleaver",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/002-cleaver.svg" },
			 new Product { Name = "Apron",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/003-apron.svg" },
			 new Product { Name = "Caviar",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/003-caviar.svg" },
			 new Product { Name = "Beef",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/004-beef-1.svg" },
			 new Product { Name = "Claw",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/004-claw.svg" },
			 new Product { Name = "Carving",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/005-carving.svg" },
			 new Product { Name = "Crab",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/005-crab.svg" },
			 new Product { Name = "Chicken",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/006-chicken.svg" },
			 new Product { Name = "Fried",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/006-fried-fish.svg" },
			 new Product { Name = "Cloche",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/007-cloche.svg" },
			 new Product { Name = "Dolly",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/007-dolly-fish.svg" },
			 new Product { Name = "Chicken",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/008-chicken-wings.svg" },
			 new Product { Name = "Eel",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/008-eel.svg" },
			 new Product { Name = "Cleaver",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/009-cleaver-1.svg" },
			 new Product { Name = "Fish",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/009-fish.svg" },
			 new Product { Name = "Jellyfish",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/010-jellyfish.svg" },
			 new Product { Name = "Meatloaf",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/010-meatloaf.svg" },
			 new Product { Name = "Kazunoko",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/011-kazunoko.svg" },
			 new Product { Name = "Salt",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/011-salt.svg" },
			 new Product { Name = "Buffalo",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/012-buffalo.svg" },
			 new Product { Name = "Lobster",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/012-lobster.svg" },
			 new Product { Name = "Mackerel",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/013-mackerel.svg" },
			 new Product { Name = "Pork",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/013-pork-leg.svg" },
			 new Product { Name = "Duck",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/014-duck.svg" },
			 new Product { Name = "Mussel",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/014-mussel.svg" },
			 new Product { Name = "Goat",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/015-goat.svg" },
			 new Product { Name = "Oyster",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/015-oyster.svg" },
			 new Product { Name = "Pickles",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/016-pickles.svg" },
			 new Product { Name = "Sausages",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/016-sausages.svg" },
			 new Product { Name = "Ketchup",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/017-ketchup.svg" },
			 new Product { Name = "Puffer",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/017-puffer-fish.svg" },
			 new Product { Name = "Cow",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/018-cow.svg" },
			 new Product { Name = "Roll",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/018-roll-fish.svg" },
			 new Product { Name = "Fillet",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/019-fillet.svg" },
			 new Product { Name = "Salmon",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/019-salmon.svg" },
			 new Product { Name = "Bacon",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/020-bacon-strips.svg" },
			 new Product { Name = "Sardine",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/020-sardine.svg" },
			 new Product { Name = "French",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/021-french-knife.svg" },
			 new Product { Name = "Sashimi",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/021-sashimi.svg" },
			 new Product { Name = "Meat",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/022-meat.svg" },
			 new Product { Name = "Sea",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/022-sea-urchin.svg" },
			 new Product { Name = "Chef",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/023-chef-hat.svg" },
			 new Product { Name = "Seafood",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/023-seafood.svg" },
			 new Product { Name = "Salami",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/024-salami.svg" },
			 new Product { Name = "Sauce",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/024-sauce.svg" },
			 new Product { Name = "Chicken",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/025-chicken-1.svg" },
			 new Product { Name = "Seaweed",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/025-seaweed.svg" },
			 new Product { Name = "Lamb",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/026-lamb.svg" },
			 new Product { Name = "Shark",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/026-shark.svg" },
			 new Product { Name = "Sheep",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/027-sheep.svg" },
			 new Product { Name = "Shrimp",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/027-shrimp-1.svg" },
			 new Product { Name = "Knife",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/028-knife.svg" },
			 new Product { Name = "Shrimp",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/028-shrimp-2.svg" },
			 new Product { Name = "Glove",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/029-glove.svg" },
			 new Product { Name = "Squid",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/029-squid.svg" },
			 new Product { Name = "Beef",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/030-beef-2.svg" },
			 new Product { Name = "Squid",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/030-squid-1.svg" },
			 new Product { Name = "Beef",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/031-beef-3.svg" },
			 new Product { Name = "Steamed",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/031-steamed.svg" },
			 new Product { Name = "Fork",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/032-fork.svg" },
			 new Product { Name = "Store",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/032-store.svg" },
			 new Product { Name = "Rooster",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/033-rooster.svg" },
			 new Product { Name = "Sushi",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/033-sushi.svg" },
			 new Product { Name = "Sausages",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/034-sausages-1.svg" },
			 new Product { Name = "Tentacles",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/034-tentacles.svg" },
			 new Product { Name = "Butcher",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/035-butcher.svg" },
			 new Product { Name = "Tom",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/035-tom-yum.svg" },
			 new Product { Name = "Butcher",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/036-butcher-shop.svg" },
			 new Product { Name = "Tuna",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/036-tuna.svg" },
			 new Product { Name = "Sirloin",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/037-sirloin-steak.svg" },
			 new Product { Name = "Cutting",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/038-cutting-board.svg" },
			 new Product { Name = "Tenderizer",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/039-tenderizer.svg" },
			 new Product { Name = "Burger",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/040-burger.svg" },
			 new Product { Name = "Premium",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/041-premium-sausage.svg" },
			 new Product { Name = "Meat",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/042-meat-grinder.svg" },
			 new Product { Name = "Pig",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/043-pig.svg" },
			 new Product { Name = "Axe",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/044-axe.svg" },
			 new Product { Name = "Kitchen",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/045-kitchen-scale.svg" },
			 new Product { Name = "Skewer",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/046-skewer.svg" },
			 new Product { Name = "Ribs",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/047-ribs.svg" },
			 new Product { Name = "Turkey",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/048-turkey.svg" },
			 new Product { Name = "Rabbit",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/049-rabbit.svg" },
			 new Product { Name = "Roasted",  Category = "Meat & Fish", Quantity = 1, Icon = "/icons/Meat__&__Fish/050-roasted-chicken.svg" },
			 new Product { Name = "Bubble Tea",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/001-bubble__tea.svg" },
			 new Product { Name = "Coxinha",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/001-coxinha.svg" },
			 new Product { Name = "Carrot Cake",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/002-carrot__cake.svg" },
			 new Product { Name = "Corndog",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/002-corndog.svg" },
			 new Product { Name = "Pretzel",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/003-pretzel.svg" },
			 new Product { Name = "Strawberry Cake",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/003-strawberry__cake.svg" },
			 new Product { Name = "Churros",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/004-churros.svg" },
			 new Product { Name = "Roll Cake",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/004-roll__cake.svg" },
			 new Product { Name = "Birthday Cake",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/005-birthday__cake.svg" },
			 new Product { Name = "Samosa",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/005-samosa.svg" },
			 new Product { Name = "Candy Cane",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/006-candy__cane.svg" },
			 new Product { Name = "Stroopwafel",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/006-stroopwafel.svg" },
			 new Product { Name = "Caramelized Apple",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/007-caramelized__apple.svg" },
			 new Product { Name = "Hot Dog",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/007-hot__dog.svg" },
			 new Product { Name = "Candy Jar",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/008-candy__jar.svg" },
			 new Product { Name = "Chimney Cake",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/008-chimney__cake.svg" },
			 new Product { Name = "Candy Stick",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/009-candy__stick.svg" },
			 new Product { Name = "Sausage",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/009-sausage.svg" },
			 new Product { Name = "French Fries",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/010-french__fries.svg" },
			 new Product { Name = "Ring Pop",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/010-ring__pop.svg" },
			 new Product { Name = "Dango",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/011-dango.svg" },
			 new Product { Name = "Lollipop",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/011-lollipop.svg" },
			 new Product { Name = "Candy",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/012-candy.svg" },
			 new Product { Name = "Takoyaki",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/012-takoyaki.svg" },
			 new Product { Name = "Chewing Gum",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/013-chewing__gum.svg" },
			 new Product { Name = "Donut",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/013-donut.svg" },
			 new Product { Name = "Burrito",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/014-burrito.svg" },
			 new Product { Name = "Potato Chips",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/014-potato__chips.svg" },
			 new Product { Name = "Cocoa",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/015-cocoa.svg" },
			 new Product { Name = "Cookies",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/015-cookies.svg" },
			 new Product { Name = "Chocolate Bar",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/016-chocolate__bar.svg" },
			 new Product { Name = "Kozinaki",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/016-kozinaki.svg" },
			 new Product { Name = "Fondue",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/017-fondue.svg" },
			 new Product { Name = "Popcorn",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/017-popcorn.svg" },
			 new Product { Name = "Churros",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/018-churros.svg" },
			 new Product { Name = "Noodles",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/018-noodles.svg" },
			 new Product { Name = "Biscuit",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/019-biscuit.svg" },
			 new Product { Name = "Cinnamon Roll",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/019-cinnamon__roll.svg" },
			 new Product { Name = "Cookies",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/020-cookies.svg" },
			 new Product { Name = "Tacos",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/020-tacos.svg" },
			 new Product { Name = "Bagel",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/021-bagel.svg" },
			 new Product { Name = "Cotton Candy",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/021-cotton__candy.svg" },
			 new Product { Name = "Crepe",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/022-crepe.svg" },
			 new Product { Name = "Crisps",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/022-crisps.svg" },
			 new Product { Name = "Croissant",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/023-croissant.svg" },
			 new Product { Name = "Peanut Butter",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/023-peanut__butter.svg" },
			 new Product { Name = "Cupcake",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/024-cupcake.svg" },
			 new Product { Name = "Wafer",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/024-wafer.svg" },
			 new Product { Name = "Custard",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/025-custard.svg" },
			 new Product { Name = "Wafer",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/025-wafer.svg" },
			 new Product { Name = "Donut",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/026-donut.svg" },
			 new Product { Name = "Macaron",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/026-macaron.svg" },
			 new Product { Name = "Eclair",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/027-eclair.svg" },
			 new Product { Name = "Karaage",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/027-karaage.svg" },
			 new Product { Name = "Gingerbread Man",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/028-gingerbread__man.svg" },
			 new Product { Name = "Nuts",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/028-nuts.svg" },
			 new Product { Name = "Candy Machine",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/029-candy__machine.svg" },
			 new Product { Name = "Soda Bottle",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/029-soda__bottle.svg" },
			 new Product { Name = "Honeycomb",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/030-honeycomb.svg" },
			 new Product { Name = "Soda Can",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/030-soda__can.svg" },
			 new Product { Name = "Honey Jar",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/031-honey__jar.svg" },
			 new Product { Name = "Pistachio",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/031-pistachio.svg" },
			 new Product { Name = "Chocolate Bar",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/032-chocolate__bar.svg" },
			 new Product { Name = "Ice Cream",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/032-ice__cream.svg" },
			 new Product { Name = "Canape",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/033-canape.svg" },
			 new Product { Name = "Popsicle Stick",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/033-popsicle__stick.svg" },
			 new Product { Name = "Ice Cream Sandwich",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/034-ice__cream sandwich.svg" },
			 new Product { Name = "Jiaozi",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/034-jiaozi.svg" },
			 new Product { Name = "Cookies",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/035-cookies.svg" },
			 new Product { Name = "Sundae",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/035-sundae.svg" },
			 new Product { Name = "Jelly Beans",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/036-jelly__beans.svg" },
			 new Product { Name = "Shaobing",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/036-shaobing.svg" },
			 new Product { Name = "Gummy Bear",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/037-gummy__bear.svg" },
			 new Product { Name = "Juice Box",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/037-juice__box.svg" },
			 new Product { Name = "Bruschetta",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/038-bruschetta.svg" },
			 new Product { Name = "Jelly",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/038-jelly.svg" },
			 new Product { Name = "Candies",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/039-candies.svg" },
			 new Product { Name = "Caramel Apple",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/039-caramel__apple.svg" },
			 new Product { Name = "Lollipop",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/040-lollipop.svg" },
			 new Product { Name = "Nachos",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/040-nachos.svg" },
			 new Product { Name = "Kimbap",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/041-kimbap.svg" },
			 new Product { Name = "Macarons",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/041-macarons.svg" },
			 new Product { Name = "Marshmallow",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/042-marshmallow.svg" },
			 new Product { Name = "Nigiri",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/042-nigiri.svg" },
			 new Product { Name = "Oden",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/043-oden.svg" },
			 new Product { Name = "Pancake",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/043-pancake.svg" },
			 new Product { Name = "Panna Cotta",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/044-panna__cotta.svg" },
			 new Product { Name = "Sandwich",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/044-sandwich.svg" },
			 new Product { Name = "Apple Pie",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/045-apple__pie.svg" },
			 new Product { Name = "Cereals",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/045-cereals.svg" },
			 new Product { Name = "Pretzel",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/046-pretzel.svg" },
			 new Product { Name = "Yakitori",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/046-yakitori.svg" },
			 new Product { Name = "Baklava",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/047-baklava.svg" },
			 new Product { Name = "Smoothie",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/047-smoothie.svg" },
			 new Product { Name = "Falafel",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/048-falafel.svg" },
			 new Product { Name = "Truffle",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/048-truffle.svg" },
			 new Product { Name = "Ice Cream Cone",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/049-ice__cream cone.svg" },
			 new Product { Name = "Wafer",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/049-wafer.svg" },
			 new Product { Name = "Cupcake",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/050-cupcake.svg" },
			 new Product { Name = "Waffle",  Category = "Sweets & Candies", Quantity = 1, Icon = "/icons/Sweets__&__Candies/050-waffle.svg" },
			 new Product { Name = "A",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/001-A.svg" },
			 new Product { Name = "B",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/002-b.svg" },
			 new Product { Name = "C",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/003-c.svg" },
			 new Product { Name = "C",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/004-c.svg" },
			 new Product { Name = "D",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/005-d.svg" },
			 new Product { Name = "E",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/006-e.svg" },
			 new Product { Name = "F",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/007-f.svg" },
			 new Product { Name = "G",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/008-g.svg" },
			 new Product { Name = "H",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/009-h.svg" },
			 new Product { Name = "I",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/010-I.svg" },
			 new Product { Name = "J",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/011-j.svg" },
			 new Product { Name = "K",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/012-k.svg" },
			 new Product { Name = "L",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/013-l.svg" },
			 new Product { Name = "M",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/014-m.svg" },
			 new Product { Name = "N",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/015-n.svg" },
			 new Product { Name = "N",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/016-n.svg" },
			 new Product { Name = "O",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/017-o.svg" },
			 new Product { Name = "P",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/018-p.svg" },
			 new Product { Name = "Q",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/019-q.svg" },
			 new Product { Name = "R",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/020-r.svg" },
			 new Product { Name = "S",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/021-s.svg" },
			 new Product { Name = "T",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/022-t.svg" },
			 new Product { Name = "U",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/023-u.svg" },
			 new Product { Name = "V",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/024-v.svg" },
			 new Product { Name = "W",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/025-w.svg" },
			 new Product { Name = "X",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/026-x.svg" },
			 new Product { Name = "Y",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/027-y.svg" },
			 new Product { Name = "Z",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/028-z.svg" },
			 new Product { Name = "Ch",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/029-ch.svg" },
			 new Product { Name = "A",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/030-A.svg" },
			 new Product { Name = "E",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/031-e.svg" },
			 new Product { Name = "I",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/032-I.svg" },
			 new Product { Name = "O",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/033-o.svg" },
			 new Product { Name = "U",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/034-u.svg" },
			 new Product { Name = "1",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/035-1.svg" },
			 new Product { Name = "2",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/036-2.svg" },
			 new Product { Name = "3",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/037-3.svg" },
			 new Product { Name = "4",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/038-4.svg" },
			 new Product { Name = "5",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/039-5.svg" },
			 new Product { Name = "6",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/040-6.svg" },
			 new Product { Name = "7",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/041-7.svg" },
			 new Product { Name = "8",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/042-8.svg" },
			 new Product { Name = "9",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/043-9.svg" },
			 new Product { Name = "0",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/044-0.svg" },
			 new Product { Name = "10",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/045-10.svg" },
			 new Product { Name = "Infinity",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/046-infinity.svg" },
			 new Product { Name = "Hashtag",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/047-hashtag.svg" },
			 new Product { Name = "Asterisk",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/048-asterisk.svg" },
			 new Product { Name = "Exclamation Mark",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/049-exclamation__mark.svg" },
			 new Product { Name = "Alphabet",  Category = "Uncategorized", Quantity = 1, Icon = "/icons/Uncategorized/050-alphabet.svg" },

		};

        public static ProductInventory Instance
        {
            get 
            {
                if (instance == null)
                {
                    instance = new ProductInventory();
                }
                return instance;
            }
        }

        public List<Product> FilterProductsByName(string searchName)
        {
            return products.Where(p => p.Name.ToLower().Contains(
                searchName.ToLower()) && 
                searchName.Length > 2
            ).ToList();
        }

        public List<Product> FilterProductsByCategory(string searchCategory)
        {
            return products.Where(p => p.Category.ToLower().Contains(
                searchCategory.ToLower()) &&
                searchCategory.Length > 2
            ).ToList();
        }

        public List<Product> GetInventory()
        {
            return products;
        }
    }
}
